name: Vuln scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: json
          output: trivy-results.json
      - uses: docker://openpolicyagent/opa:0.34.2-rootless
        with:
          args: "eval -f pretty -b .github/workflows -i trivy-results.json --fail-defined data.vuln.failed"
